version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-test
    restart: always
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: panda
